### ISSUE TITLE
这个key走哪里来的呢？？、

### ISSUE THREAD

**Issue by 623636245** [zq99299/vuepress-plugin#6]

**Comment by zq99299** [comment]
key: 在百度统计中心申请的 key
你看这个地址的说明：https://github.com/zq99299/vuepress-plugin/tree/master/vuepress-plugin-baidu-tongji-analytics

**Comment by 623636245** [comment]
噢噢对的。之前没科学上网，图片没加载出来，现在可以了，谢谢
